# fly.toml app configuration file generated for holy-bush-3386 on 2023-08-19T14:37:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holy-bush-3386"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "1h"
  method = "GET"
  timeout = "5s"
  path = "/health"
